class Fire:
    conversation = [
        "FIRE-PR",
        "FIRE program for Puerto Rico",
        "Script usage for FIRE-PR?",
        "perl genDataPR.pl -taxYear=<tax_year> -clientId=<client_id> -formType=<4806D|4806A|4806B|4806C> -rootDir=<root_dir> [--refresh_payer=Y] [--preStmtProduction] [--testIRSFile=Y] --prFileDate=<yyyy-mm-dd>",
        "How do accounts get added to AccountHoldersPR on a regular basis? When are transactions assigned PR form and box?",
        "Through TransData validation. It takes care of updating AHPR and PR form box assignment.",
        "If there are changes to AH or SM changes, how will that be picked up?",
        "Through Delta process which will run on daily basis and will pick up any change in AH/SM and will take care of updating AccountholdersPR table and PR form box assignment",
        "How can I force the process to re-evaluate the PR form/box values? ",
        "Yes, it can be done by changing the AHPR CreateDt of an account to earlier date, after that it can be picked up by either validations/delta process.",
        "How can I get the control number estimates/list of accounts which will be pended during next run?",
        "Run the process in check Deminimus status mode for all the accounts, in the end it will give you number of accounts pended per form. Also, you can see the complete list of accounts at irsInput/pended.txt.991231 for each form",
        "Do I need to run for specific forms 4806A/4806B/4806C/4806D?",
        "No, all the forms will be running in parallel and we will have o/p for all the forms.",
        "If I force pend accounts, will they be pended and present in FIRE file? ",
        "If you forcePend any specific account, it will check for valid Transactions and if data is present it will be force pended. This will be used during correction runs.",
        "Will PendingStatus gets updated in ReportingFlags during PR Check Deminius Status mode?",
        "No. We only get the number of accounts per form. No FIRE file is generated, RF won't be updated.",
         "FIRE",
    "Filing Income Returns Electronically.",
    "",
    "1042S_IRS.pl -taxYear=<taxYear> -clientId=<clientId> -rootDir=<root dir> [-previousRun=<yyyymmdd>] [-testIRSFile=Y|N] [-irsFileDate=<yyyy-mm-dd>] [-correctionOnly=<correction run date>] [-deleteDate=<delete date>] [--preStmtProduction] [-fireProcessId={Id from FIREProcessInfo table}]",
    "script usage for 1099R?",
    "perl irsFile.pl -taxYear=<taxYear> -clientId=<clientId>  -formType<1099R|1099Q|5498|5498ESA|5498SA|1099SA|1098|1099LTC> [-stateCode= <StateCode] -rootDir=<root dir> [-testIRSFile=Y|N] [-ofxFlag=Y|N] [-ofxLastExtractDate=<yyyymmdd>] [--loadDataInMysql] [-previousRun=<yyyymmdd>]  [-irsFileDate=<yyyymmdd>] [-correctionOnly=<correction run date>] [--forceOption] [--preStmtProduction]  [-deleteDate=<delete date>] -logConfig <name of log4perl config file> [-refresh_payer=Y|N] [-fireProcessId=<Id from FIREProcessInfo>] [--refreshState]",
    "script usage for 1099IRS filing?",
    "perl IRS.pl --taxYear 2011 --clientId sm3 --ofxFlag Y --ofxLastExtractDate 2012-07-31 --rootDir /opt/taxgard/reports/IRS/",
    "BFS package",
    "https://confluence.wsc.com:8091/display/CP/BroadRidge+Print+Requirements",
    "WSC website",
    "https://www.wsc.com",
    "SCorp statements",
    "Scorp statements are reportable and non-reportable 1099Statements stitched together. Do you want to know the Account selection criteria?",
    "Yes",
    "Accounts with DomRptInd as C, D, J can only create Scorp statements",
    "How to set-up packaging routine for a client?",
    "Packaging function is set-up in RptCmdList table.",
    "where can I reset my e-login password",
    "https://oracle.fnfis.com"
    ]